/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PersonalTrainingRouteImport } from './routes/personal-training'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassesIndexRouteImport } from './routes/classes.index'
import { Route as ClassesScheduleRouteImport } from './routes/classes.schedule'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalTrainingRoute = PersonalTrainingRouteImport.update({
  id: '/personal-training',
  path: '/personal-training',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesIndexRoute = ClassesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassesRoute,
} as any)
const ClassesScheduleRoute = ClassesScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ClassesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classes': typeof ClassesRouteWithChildren
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/memberships': typeof MembershipsRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/classes/schedule': typeof ClassesScheduleRoute
  '/classes/': typeof ClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/memberships': typeof MembershipsRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/classes/schedule': typeof ClassesScheduleRoute
  '/classes': typeof ClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classes': typeof ClassesRouteWithChildren
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/memberships': typeof MembershipsRoute
  '/personal-training': typeof PersonalTrainingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/classes/schedule': typeof ClassesScheduleRoute
  '/classes/': typeof ClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/classes'
    | '/contact'
    | '/facility'
    | '/memberships'
    | '/personal-training'
    | '/sitemap.xml'
    | '/classes/schedule'
    | '/classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/facility'
    | '/memberships'
    | '/personal-training'
    | '/sitemap.xml'
    | '/classes/schedule'
    | '/classes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/classes'
    | '/contact'
    | '/facility'
    | '/memberships'
    | '/personal-training'
    | '/sitemap.xml'
    | '/classes/schedule'
    | '/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClassesRoute: typeof ClassesRouteWithChildren
  ContactRoute: typeof ContactRoute
  FacilityRoute: typeof FacilityRoute
  MembershipsRoute: typeof MembershipsRoute
  PersonalTrainingRoute: typeof PersonalTrainingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-training': {
      id: '/personal-training'
      path: '/personal-training'
      fullPath: '/personal-training'
      preLoaderRoute: typeof PersonalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes/': {
      id: '/classes/'
      path: '/'
      fullPath: '/classes/'
      preLoaderRoute: typeof ClassesIndexRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/classes/schedule': {
      id: '/classes/schedule'
      path: '/schedule'
      fullPath: '/classes/schedule'
      preLoaderRoute: typeof ClassesScheduleRouteImport
      parentRoute: typeof ClassesRoute
    }
  }
}

interface ClassesRouteChildren {
  ClassesScheduleRoute: typeof ClassesScheduleRoute
  ClassesIndexRoute: typeof ClassesIndexRoute
}

const ClassesRouteChildren: ClassesRouteChildren = {
  ClassesScheduleRoute: ClassesScheduleRoute,
  ClassesIndexRoute: ClassesIndexRoute,
}

const ClassesRouteWithChildren =
  ClassesRoute._addFileChildren(ClassesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClassesRoute: ClassesRouteWithChildren,
  ContactRoute: ContactRoute,
  FacilityRoute: FacilityRoute,
  MembershipsRoute: MembershipsRoute,
  PersonalTrainingRoute: PersonalTrainingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
